imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ PicdumpDemoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        #cssembed:
        #  jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        #yui_js:
        # jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        lessphp:
          file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
          apply_to: "\.less$"

    assets:
        jquery_js:
              inputs:
                  - '%kernel.root_dir%/../web/bundles/picdumpdemo/js/jquery.js'
        bootstrap_js:
              inputs:
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-transition.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-alert.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-modal.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-dropdown.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-scrollspy.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-tab.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-tooltip.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-popover.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-button.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-collapse.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-carousel.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-typeahead.js'
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/js/bootstrap-affix.js'
        bootstrap_less:
               inputs:
                  - '%kernel.root_dir%/../vendor/twitter/bootstrap/twitter/bootstrap/less/bootstrap.less'
               filters: [lessphp]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

avalanche_imagine:
    filters:
        thumbs:
            type:    thumbnail
            options: { size: [200, 200], mode: outbound }
        display:
            type:    thumbnail
            options: { size: [1920, 1080], mode: inset }
