_welcome:
    pattern:  /
    defaults: { _controller: PicdumpDemoBundle:Welcome:index }

_demo_secured:
    resource: "@PicdumpDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@PicdumpDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
